/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomRadio {
        /**
          * Whether or not the radio is disabled.
         */
        "disabled": boolean;
    }
}
declare global {
    interface HTMLCustomRadioElement extends Components.CustomRadio, HTMLStencilElement {
    }
    var HTMLCustomRadioElement: {
        prototype: HTMLCustomRadioElement;
        new (): HTMLCustomRadioElement;
    };
    interface HTMLElementTagNameMap {
        "custom-radio": HTMLCustomRadioElement;
    }
}
declare namespace LocalJSX {
    interface CustomRadio {
        /**
          * Whether or not the radio is disabled.
         */
        "disabled"?: boolean;
    }
    interface IntrinsicElements {
        "custom-radio": CustomRadio;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-radio": LocalJSX.CustomRadio & JSXBase.HTMLAttributes<HTMLCustomRadioElement>;
        }
    }
}
